language: python
services:
  - postgresql
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - pip install -r requirements.txt
before_script:
  - psql -c 'create database crft;' -U postgres
script: django-admin.py migrate
